### ISSUE TITLE
shall we raise an error or just warning

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#141]
https://github.com/marrlab/DomainLab/blob/7d8b83a8870cfe1c904b385741a4e37937ac2970/domainlab/exp_protocol/run_experiment.py#L44

@schoersch

**Comment by schoersch** [comment]
I'm not sure what's better. Currently, the command line args translate like this:
1. `--x=1` -> `x: 1`
2. `--x 1 2` -> 
```
x:
  - 1
  - 2
```
So the user has to create lists rather explicit, which let me tend to a warning. On the other hand, if the conversions happens unintentionally, it will likely lead to subsequent errors which are hard to pinpoint down to this warning.

**Comment by schoersch** [comment]
I also thought again about this warning:
https://github.com/marrlab/DomainLab/blob/7d8b83a8870cfe1c904b385741a4e37937ac2970/domainlab/exp_protocol/run_experiment.py#L55
Unknown keys are silently ignored for the reasons I pointed out already. However, this is also the reason while the `bs != batchsize` error hasn't shown up for such a long time.
One idea I had to resolve this would be, that we filter the dictionaries passed to this function by removing all benchmark specific keys. Since this is a known set, only keys that should be passed on to domainlab should remain. Then we can securely raise an error if a unknown key is given.
Moreover, this function can then also be used here
https://github.com/marrlab/DomainLab/blob/7d8b83a8870cfe1c904b385741a4e37937ac2970/domainlab/arg_parser.py#L171
to reduce code duplication.

I can make a PR for this proposal.

**Comment by schoersch** [comment]
A problem determining the set of all benchmark specific keys is that all snakemake keys (i.e. commandline options) need to be contained in it.

So maybe a better option would be, that we introduce a `domainlab_args` section, e.g.

```
...
# benchmark and snakemake related stuff
# domainlab specific settings given here are ignored.
output_dir: dir
....
domainlab_args:
  # here only valid domainlab names are allowed.
  lr: 1e-3
  te_d: 5
  ...

Task_x:
   # Arguments specific to this task. Same as currently, arguments
   # here overwrite specifications of the domainlab_args part.
   aname: algo
   # also here, inside the task, only domainlab valid arguments can be specified,
   # except the hyperparameters block.
   ....
```
@smilesun what do you think?
