### ISSUE TITLE
rename task in benchmark setting

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#223]
the word task is a bit confusing, as in the benchmark, task means a section in the configuration file like below, essentially, one section like below correspond to one algorithm's hyper-parameter setting to be searched for. 

```
hduva:  # name
  aname: hduva
  npath: examples/nets/resnet.py
  nname_topic_distrib_img2topic: conv_bn_pool_2
  nname_encoder_sandwich_layer_img2h4zd: conv_bn_pool_2

  hyperparameters:
    gamma_y:
      min: 7e4
      max: 7e6
      step: 1
      distribution: loguniform

    zy_dim:
      min: 32
      max: 128
      step: 4
      distribution: loguniform

deep_all:
  aname: deepall
  nname: alexnet
```
