### ISSUE TITLE
check if constant hyper-parameters are being respected in experiments

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#338]
suppose we have something like, do we have a unit test to make sure zx_dim is always set to zero in all runs for HDUVA? 

```
method_hduva:  # name
  aname: hduva

  nname_topic_distrib_img2topic: conv_bn_pool_2
  nname_encoder_sandwich_layer_img2h4zd: conv_bn_pool_2
  shared:
    - gamma_y
    - zy_dim
  zx_dim: 0
  zd_dim: 32
```
