### ISSUE TITLE
output error if one hyperparameter is specified twice for a method

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#381]
In the following configuration,  `zx_dim` is specified to be fixed value 0 and then in the hyperparameter again, in this case, an error should be raised. 

```
method_diva:  # name
  aname: diva
  zx_dim: 0
  zd_dim: 32
  shared:
    - gamma_y
    - zy_dim
  nname_dom: conv_bn_pool_2

  hyperparameters:
    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform
      num: 2
    zx_dim:
      min: 0
      max: 96
      step: 32
      distribution: uniform
      num: 2
      datatype: int

```
