### ISSUE TITLE
the following yaml file 1e5 is regareded as string instead of float

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#429]
```
mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt

num_param_samples: 8
sampling_seed: 0
startseed: 0
endseed: 2

test_domains:
  - 3
  - 0


domainlab_args:
  task: mnistcolor10
  tr_d: [1, 2]
  dmem: False
  lr: 0.001
  epos: 3
  es: 5
  bs: 64
  nname: conv_bn_pool_2
  san_check: True
  exp_shoulder_clip: 10
  mu_clip: 1e4
  coeff_ma: 0.5


Shared params:
  ini_setpoint_ratio:
    min: 0.5
    max: 0.99
    num: 5
    step: 0.05
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    step: 0.0001
    distribution: uniform

# Test fbopt with different hyperparameter configurations

jigen_fbopt:
  aname: jigen
  trainer: fbopt

  shared:
    - ini_setpoint_raio
```
