### ISSUE TITLE
hyper-parameter out of range

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#497]
`commit c29d52ca402eb928bcf3cf7e9ca8398ad2ebb7c7 (HEAD -> fbopt, origin/fbopt)
`

 `./run_benchmark_standalone.sh examples/benchmark/benchmark_fbopt_pacs_jigen.yaml`

we get
```

cat zoutput/benchmarks/benchmark_fbopt_pacs_full/hyperparameters.csv 
,task,algo,params
0,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9166666666666667, 'k_i_gain': 0.00031622776601683794, 'mu_init': 0.0031622776601683794}"
1,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9166666666666667, 'k_i_gain': 0.00031622776601683794, 'mu_init': 0.09999999999999999}"
2,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9166666666666667, 'k_i_gain': 0.00031622776601683794, 'mu_init': 3.162277660168379}"
3,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9166666666666667, 'k_i_gain': 0.03162277660168379, 'mu_init': 0.0031622776601683794}"
4,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9166666666666667, 'k_i_gain': 0.03162277660168379, 'mu_init': 0.09999999999999999}"
5,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9166666666666667, 'k_i_gain': 0.03162277660168379, 'mu_init': 3.162277660168379}"
6,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9500000000000001, 'k_i_gain': 0.00031622776601683794, 'mu_init': 0.0031622776601683794}"
7,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9500000000000001, 'k_i_gain': 0.00031622776601683794, 'mu_init': 0.09999999999999999}"
8,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9500000000000001, 'k_i_gain': 0.00031622776601683794, 'mu_init': 3.162277660168379}"
9,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9500000000000001, 'k_i_gain': 0.03162277660168379, 'mu_init': 0.0031622776601683794}"
10,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9500000000000001, 'k_i_gain': 0.03162277660168379, 'mu_init': 0.09999999999999999}"
11,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9500000000000001, 'k_i_gain': 0.03162277660168379, 'mu_init': 3.162277660168379}"
12,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9833333333333334, 'k_i_gain': 0.00031622776601683794, 'mu_init': 0.0031622776601683794}"
13,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9833333333333334, 'k_i_gain': 0.00031622776601683794, 'mu_init': 0.09999999999999999}"
14,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9833333333333334, 'k_i_gain': 0.00031622776601683794, 'mu_init': 3.162277660168379}"
15,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9833333333333334, 'k_i_gain': 0.03162277660168379, 'mu_init': 0.0031622776601683794}"
16,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9833333333333334, 'k_i_gain': 0.03162277660168379, 'mu_init': 0.09999999999999999}"
17,jigen_fbopt,jigen,"{'ini_setpoint_ratio': 0.9833333333333334, 'k_i_gain': 0.03162277660168379, 'mu_init': 3.162277660168379}"

```

but the yaml file is

```


 cat examples/benchmark/benchmark_fbopt_pacs_jigen.yaml 
mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt_pacs_full

sampling_seed: 0

startseed: 0
endseed: 1

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_path_list.py
  dmem: False
  lr: 5e-5
  epos: 200
  es: 20
  bs: 64
  san_check: False
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  npath_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py
  exp_shoulder_clip: 10
  mu_clip: 10_000
  coeff_ma: 0.5
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64




Shared params:
  ini_setpoint_ratio:
    min: 0.9
    max: 1.0
    num: 3
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    distribution: loguniform

  mu_init:
    min: 0.001
    max: 1.0
    num: 3
    distribution: loguniform

# Test fbopt with different hyperparameter configurations

jigen_fbopt:
  aname: jigen
  trainer: fbopt
  shared:
    - ini_setpoint_ratio
    - k_i_gain
    - mu_init
```
