### ISSUE TITLE
bug with categorical data in benchmark 

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#522]
InputFunctionException in rule agg_results in file /home/sunxd/domainlab/domainlab/exp_protocol/benchmark.smk, line 155:                                                                                                                                                                  
Error:                                                                                                                                                                                                                                                                                    
  KeyError: 'datatype'                                                                                                                                                                                                                                                                    
Wildcards:                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                          
Traceback:
  File "/home/sunxd/domainlab/domainlab/exp_protocol/benchmark.smk", line 38, in experiment_result_files
  File "/home/sunxd/domainlab/domainlab/utils/hyperparameter_gridsearch.py", line 339, in sample_gridsearch
  File "/home/sunxd/domainlab/domainlab/utils/hyperparameter_gridsearch.py", line 287, in grid_task
  File "/home/sunxd/domainlab/domainlab/utils/hyperparameter_gridsearch.py", line 200, in sample_grid
  File "/home/sunxd/domainlab/domainlab/utils/hyperparameter_sampling.py", line 148, in __init__



```
mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt

sampling_seed: 0
startseed: 0
endseed: 4

test_domains:
  - 0


domainlab_args:
  task: mnistcolor10
  tr_d: [1, 2]
  dmem: False
  lr: 0.001
  epos: 500
  es: 100
  bs: 64
  nname: conv_bn_pool_2
  san_check: False
  exp_shoulder_clip: 10
  mu_clip: 10
  coeff_ma: 0.5
  no_tensorboard: False
  pperm: 0.5



Shared params:
  setpoint_rewind:
    distribution: categorical
    values:
    - "yes"
    - "no"
  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    distribution: uniform

  mu_init:
    min: 0.000001
    max: 0.00001
    num: 3
    distribution: loguniform

  gamma_reg:
    min: 0.01
    max: 10_000
    num: 10
    distribution: loguniform



# Test fbopt with different hyperparameter configurations

jigen_feedback:
  aname: jigen
  trainer: fbopt
  ini_setpoint_ratio: 0.99
  shared:
    - k_i_gain
    - mu_init

```
