### ISSUE TITLE
cache for dependencies

### ISSUE THREAD

**Issue by ntchen** [marrlab/DomainLab#747]
do we want to cache to make CI test faster?

```
  - name: Cache Python dependencies
    uses: actions/cache@v2
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-
```

in `.github/workflows/ci.yml`
